---
version: 2
project_name: tfrstate

archives:
  - name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*

builds:
  - binary: tfrstate
    main: cmd/tfrstate/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

release:
  prerelease: "true"
  header: |
    [Pull Requests](https://github.com/suzuki-shunsuke/tfrstate/pulls?q=is%3Apr+milestone%3A{{.Tag}}) | [Issues](https://github.com/suzuki-shunsuke/tfrstate/issues?q=is%3Aissue+milestone%3A{{.Tag}}) | https://github.com/suzuki-shunsuke/tfrstate/compare/{{.PreviousTag}}...{{.Tag}}

signs:
  - cmd: cosign
    artifacts: checksum
    signature: ${artifact}.sig
    certificate: ${artifact}.pem
    output: true
    args:
      - sign-blob
      - "-y"
      - --output-signature
      - ${signature}
      - --output-certificate
      - ${certificate}
      - --oidc-provider
      - github
      - ${artifact}

homebrew_casks:
  -
    # NOTE: make sure the url_template, the token and given repo (github or gitlab) owner and name are from the
    # same kind. We will probably unify this in the next major version like it is done with scoop.

    # GitHub/GitLab repository to push the formula to
    repository:
      owner: suzuki-shunsuke
      name: homebrew-tfrstate
    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    # Your app's homepage.
    # Default is empty.
    homepage: https://github.com/suzuki-shunsuke/tfrstate

    # Template of your app's description.
    # Default is empty.
    description: |
      Find directories where changed terraform_remote_state data source is used
    license: MIT

    skip_upload: true

    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfrstate"]
          end

scoops:
  -
    description: |
      Find directories where changed terraform_remote_state data source is used
    license: MIT
    skip_upload: true
    repository:
      owner: suzuki-shunsuke
      name: scoop-bucket

sboms:
  - id: default
    disable: false
